language: python
python:
  - '2.5'
  - '2.6'
  - '2.7'
  - '3.2'
  - '3.3'
  - 'pypy'    
install:
  - 'pip install -r requirements/basic.txt'
  - 'pip install -r requirements/devel.txt'
  - 'pip install -r requirements/l10n.txt'
script: ./run_tests
notifications:
  email:
    - neithere+travis@gmail.com
